---
title: "Coronavirus by County in NYS"
date: "Last updated on `r format(Sys.time(), '%m/%d/%Y at %H:%M:%S')`"
---

```{r, echo=FALSE}
knitr::opts_chunk$set(error = TRUE)
```


```{r, include = FALSE}
require(ggplot2)
require(reshape2)
require(gganimate)
require(gifski)
require(readxl, quietly = TRUE)
require(xlsx, quietly = TRUE)
require(dplyr)
require(cowplot, quietly = TRUE)
require(googleway, quietly = TRUE)
require(ggrepel, quietly = TRUE)
require(ggspatial, quietly = TRUE)
require(libwgeom, quietly = TRUE)
require(sf, quietly = TRUE)
require(rnaturalearth, quietly = TRUE)
require(rnaturalearthdata, quietly = TRUE)
library(leaflet)
library(maps)
library(htmlwidgets)

setwd("C:\\Users\\CONNO\\OneDrive\\Documents\\GitHub\\COVID")

dat <- read_excel('USCOVID_TimeSeries.xlsx',sheet = 'covid')
dat.death <- read_excel('USCOVID_TimeSeries.xlsx',sheet = 'covid_deaths')

##Removes unnecessary fields
dat.death$iso2 <- NULL
dat.death$iso3 <- NULL
dat.death$code3 <- NULL
dat.death$FIPS <- NULL
dat.death$Country_Region <- NULL


dat$iso2 <- NULL
dat$iso3 <- NULL
dat$code3 <- NULL
dat$FIPS <- NULL
dat$Country_Region <- NULL 
#############################

##Tidies Data##
dat.melt <- melt(dat, id.vars = c('UID','Admin2','Province_State', 'Lat','Long_','Combined_Key'))
dat.melt$date <- dat.melt$variable
dat.melt$variable <- NULL
dat.melt$value <- as.numeric(dat.melt$value)
dat.melt$date <- as.Date(dat.melt$date,"%m/%d/%y") ##Sets date to date type

dat.death.melt <- melt(dat.death, id.vars = c('UID','Admin2','Province_State', 'Lat','Long_','Combined_Key','Population'))
dat.death.melt$date <- dat.death.melt$variable
dat.death.melt$variable <- NULL
dat.death.melt$value <- as.numeric(dat.death.melt$value)
dat.death.melt$date <- as.Date(dat.death.melt$date,"%m/%d/%y")


## NEW YORK ONLY ##
dat.melt.NY <- dat.melt[dat.melt$Province_State == 'New York',] 
dat.death.melt.NY <- dat.death.melt[dat.death.melt$Province_State == 'New York',] ##Removes all other States

##Long Island Only##
dat.melt.LI <- dat.melt.NY[dat.melt.NY$Admin2 == 'Suffolk' | dat.melt.NY$Admin2 == 'Nassau',]
dat.melt.LI <-dat.melt.LI[dat.melt.LI$value > 1,] ##Ignores early months
dat.death.melt.LI <- dat.death.melt.NY[dat.death.melt.NY$Admin2 == 'Suffolk' | dat.death.melt.NY$Admin2 == 'Nassau',]

##Downstate Only##
dat.melt.DS <- dat.melt.NY[dat.melt.NY$Admin2 == 'Suffolk' | dat.melt.NY$Admin2 == 'Nassau'|dat.melt.NY$Admin2 == 'New York'|dat.melt.NY$Admin2 == 'Westchester'|dat.melt.NY$Admin2 == 'Rockland'|dat.melt.NY$Admin2 == 'Orange',]


## MAPS ##
dat.death.melt.NY <- dat.death.melt.NY[dat.death.melt.NY$Lat != 0,] ##Kills bad data
dat.melt.NY$Lat <- as.numeric(dat.melt.NY$Lat) ## Makes Lat/Long a numeric
dat.melt.NY$Long_ <- as.numeric(dat.melt.NY$Long_)## Makes Lat/Long a numeric
dat.melt.NY <- dat.melt.NY[dat.melt.NY$Lat != 0,]#Kills bad data

sum.ny.data.deaths <- dat.death.melt.NY %>% ## Counts as of today
  group_by(Admin2, Lat, Long_, Population) %>%
  summarise(TotalDeaths = max(value))

sum.ny.data <- dat.melt.NY %>% ## Counts as of today
  group_by(Admin2, Lat, Long_) %>%
  summarise(Total = max(value))


sum.ny.data <- merge(sum.ny.data, sum.ny.data.deaths, by = c('Admin2','Lat','Long_'))
sum.ny.data <- sum.ny.data[sum.ny.data$Total > 0, ]

sum.ny.data$pct <- round(sum.ny.data$Total/sum.ny.data$Population*100,2) ## Percent of population

sum.ny.data$pctrank <- percent_rank(sum.ny.data$pct) ##Pct Rank for size of markers


qpal <- colorNumeric("YlOrRd", sum.ny.data$pct, n = 3)

covidny <- 
  leaflet(data = sum.ny.data) %>%
  addProviderTiles('CartoDB.DarkMatterNoLabels')%>%
  addCircleMarkers(lng = ~Long_, 
                   lat = ~Lat,
                   popup = ~paste0(Admin2,
                                   '<br/>Cases: ', format(Total,big.mark=","),
                                   '<br/>Deaths:', format(TotalDeaths,big.mark=","),
                                   '<br/>% of Pop Infected: ',paste0(pct,"%")),
                   fillColor = ~qpal(pct),
                   color = ~qpal(pct), fillOpacity = .7,
                   radius = ~5 + pctrank*10,
                   label = ~Admin2)%>%
  addLegend("bottomleft", pal = qpal, values = ~pct,
            title = "% of Pop Infected")%>%
  fitBounds(lng1 = -79.8, lng2 = -72.7, lat1 = 40.5, lat2 = 44.5)


```


```{r, echo=FALSE, fig.width=14, fig.height=10}
suppressWarnings(covidny)
```